#!/bin/sh

start() {
	
	echo 133 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio133/direction
	echo 1 > /sys/class/gpio/gpio133/value
	
	modprobe 100ask_spidev
}

stop() {
	rmmod 100ask_spidev
}
case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: $0 {start| stop|restart}"
		exit 1
esac

exit $?

